# Generated by Django 3.2.9 on 2021-12-01 19:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211202_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
